-- =====================================================
-- FunaGig Database Schema (PostgreSQL)
-- Fully rewritten from MySQL to modern Postgres syntax
-- =====================================================

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- CORE TABLES
-- =====================================================

-- Users table (unified for students and businesses)
CREATE TABLE public.users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    email_verified BOOLEAN DEFAULT FALSE,
    type TEXT NOT NULL CHECK (type IN ('student', 'business')),
    university TEXT NULL,
    major TEXT NULL,
    industry TEXT NULL,
    profile_image TEXT NULL,
    bio TEXT NULL,
    skills TEXT NULL,
    location TEXT NULL,
    phone TEXT NULL,
    website TEXT NULL,
    rating NUMERIC(3,2) DEFAULT 0.00,
    total_ratings INT DEFAULT 0,
    is_verified BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Gigs table
CREATE TABLE public.gigs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    budget NUMERIC(10,2) NOT NULL,
    deadline DATE NOT NULL,
    skills TEXT NULL,
    location TEXT NULL,
    type TEXT DEFAULT 'one-time' CHECK (type IN ('one-time', 'ongoing', 'contract')),
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'paused', 'completed', 'cancelled')),
    view_count INT DEFAULT 0,
    application_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Applications table
CREATE TABLE public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    gig_id BIGINT NOT NULL REFERENCES public.gigs(id) ON DELETE CASCADE,
    message TEXT NULL,
    resume_path TEXT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'completed')),
    applied_at TIMESTAMPTZ DEFAULT NOW(),
    responded_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    rating INT NULL CHECK (rating >= 1 AND rating <= 5),
    review TEXT NULL,
    UNIQUE(user_id, gig_id)
);

-- Conversations table
CREATE TABLE public.conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    user2_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    last_message_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user1_id, user2_id)
);

-- Messages table
CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    original_content TEXT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    edited_at TIMESTAMPTZ NULL
);

-- Notifications table
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'info' CHECK (type IN ('info', 'success', 'warning', 'error')),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Saved gigs table
CREATE TABLE public.saved_gigs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    gig_id BIGINT NOT NULL REFERENCES public.gigs(id) ON DELETE CASCADE,
    saved_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, gig_id)
);

-- Skills table
CREATE TABLE public.skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    category TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User skills table
CREATE TABLE public.user_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES public.skills(id) ON DELETE CASCADE,
    proficiency TEXT DEFAULT 'intermediate' CHECK (proficiency IN ('beginner', 'intermediate', 'advanced', 'expert')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, skill_id)
);

-- Reviews table
CREATE TABLE public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewer_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    reviewee_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    application_id BIGINT NULL REFERENCES public.applications(id) ON DELETE SET NULL,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(reviewer_id, reviewee_id, application_id)
);

-- Categories table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT NULL,
    parent_id BIGINT NULL REFERENCES public.categories(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Gig categories table
CREATE TABLE public.gig_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gig_id BIGINT NOT NULL REFERENCES public.gigs(id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
    UNIQUE(gig_id, category_id)
);

-- =====================================================
-- ENHANCEMENT TABLES
-- =====================================================

-- Message attachments table
CREATE TABLE public.message_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_type TEXT NOT NULL,
    file_size INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User files table (portfolio, certificates, etc.)
CREATE TABLE public.user_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_type TEXT NOT NULL,
    file_size INT NOT NULL,
    file_category TEXT DEFAULT 'portfolio' CHECK (file_category IN ('portfolio', 'certificate', 'other')),
    description TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Gig attachments table
CREATE TABLE public.gig_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gig_id BIGINT NOT NULL REFERENCES public.gigs(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_type TEXT NOT NULL,
    file_size INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Typing indicators table
CREATE TABLE public.typing_indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    is_typing BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(conversation_id, user_id)
);

-- Analytics & Monitoring
CREATE TABLE public.analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NULL REFERENCES public.users(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    event_data JSONB NULL,
    ip_address TEXT NULL,
    user_agent TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.page_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NULL REFERENCES public.users(id) ON DELETE SET NULL,
    page_path TEXT NOT NULL,
    ip_address TEXT NULL,
    user_agent TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Interest Tracking
CREATE TABLE public.interested_gigs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    gig_id BIGINT NOT NULL REFERENCES public.gigs(id) ON DELETE CASCADE,
    interested_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, gig_id)
);

CREATE TABLE public.gig_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gig_id BIGINT NOT NULL REFERENCES public.gigs(id) ON DELETE CASCADE,
    user_id UUID NULL REFERENCES public.users(id) ON DELETE SET NULL,
    ip_address TEXT NULL,
    viewed_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- VIEWS
-- =====================================================

CREATE OR REPLACE VIEW public.active_gigs AS
SELECT g.*, u.name as business_name, u.industry, u.location as business_location
FROM public.gigs g
JOIN public.users u ON g.user_id = u.id
WHERE g.status = 'active';

CREATE OR REPLACE VIEW public.application_details AS
SELECT a.*, g.title as gig_title, g.budget, u1.name as student_name, u2.name as business_name
FROM public.applications a
JOIN public.gigs g ON a.gig_id = g.id
JOIN public.users u1 ON a.user_id = u1.id
JOIN public.users u2 ON g.user_id = u2.id;

CREATE OR REPLACE VIEW public.conversation_summary AS
SELECT c.*, 
       u1.name as user1_name, 
       u2.name as user2_name,
       (SELECT content FROM public.messages WHERE conversation_id = c.id ORDER BY created_at DESC LIMIT 1) as last_message,
       (SELECT created_at FROM public.messages WHERE conversation_id = c.id ORDER BY created_at DESC LIMIT 1) as last_message_time
FROM public.conversations c
JOIN public.users u1 ON c.user1_id = u1.id
JOIN public.users u2 ON c.user2_id = u2.id;
